# Generated by Django 5.2.6 on 2025-09-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('baverages', 'Baverages'), ('cereal', 'Cereal'), ('personalcare', 'PersonalCare'), ('cleaningsupply', 'CleaningSupply'), ('snacks', 'Snacks'), ('spicies', 'Spicies')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
